(in-package :kindista)

(declaim (optimize (speed 0) (safety 3) (debug 3)))

(defparameter *tag-scanner* (ppcre:create-scanner "^[-a-z]{3,}$"))

(defparameter *top-tags* '(
                           "activity"
                           "animal"
                           "art"
                           "book"
                           "caregiving"
                           "children"
                           "clothing"
                           "communication"
                           "design"
                           "education"
                           "entertainment"
                           "equipment"
                           "farm"
                           "food"
                           "furniture"
                           "garden"
                           "health"
                           "home"
                           "labor"
                           "law"
                           "maintenance"
                           "marine"
                           "media"
                           "office"
                           "outdoor"
                           "service"
                           "spaces"
                           "spirit"
                           "supplies"
                           "technology"
                           "tools"
                           "transportation"
                          ))

(defvar *forbidden-tags* (make-hash-table :size 750 :test 'equalp))

(defun add-forbidden-tags (&rest tags)
  (dolist (tag tags)
    (setf (gethash tag *forbidden-tags*) nil)))

(defun forbidden-tag-p (tag)
  (nth-value 1 (gethash tag *forbidden-tags*)))

(add-forbidden-tags
  "bitch"
  "anus"
  "arse"
  "arsehold"
  "ass"
  "ass-hat"
  "ass-jabber"
  "ass-pirate"
  "assbag"
  "assbandit"
  "assbanger"
  "felch"
  "skullfuck"
  "assmucus"
  "cumdump"
  "santorum"
  "shit"
  "cunt"
  "anal"
  "licker"
  "motherfucker"
  "whore"
  "fuck"
  "fucker"
  "biatch"
  "blowjob"
  "twat"
  "felching"
  "fudgepacker"
  "nigger"
  "nigga"
  "smegma"
  "turd"
  "wtf"
  "whore"
  "not"
  "like"
  "and"
  "the"
  "but"
  "able"
  "about"
  "above"
  "according"
  "accordingly"
  "across"
  "actually"
  "adj"
  "afterwards"
  "again"
  "against"
  "ago"
  "all"
  "allow"
  "allows"
  "almost"
  "along"
  "alongside"
  "already"
  "also"
  "although"
  "always"
  "amid"
  "amidst"
  "among"
  "amongst"
  "and"
  "another"
  "any"
  "anybody"
  "anyhow"
  "anything"
  "anyway"
  "anyways"
  "anywhere"
  "appear"
  "appreciate"
  "appropriate"
  "are"
  "aren't"
  "aside"
  "associated"
  "away"
  "awfully"
  "became"
  "because"
  "become"
  "becomes"
  "been"
  "believe"
  "below"
  "beside"
  "besides"
  "but"
  "came"
  "can"
  "cannot"
  "cant"
  "certainly"
  "com"
  "come"
  "comes"
  "completely"
  "concerning"
  "consequently"
  "consider"
  "considering"
  "contain"
  "containing"
  "contains"
  "corresponding"
  "could"
  "couldn't"
  "course"
  "currently"
  "dare"
  "decrease"
  "decreasingly"
  "definitely"
  "described"
  "despite"
  "did"
  "directly"
  "does"
  "done"
  "each"
  "either"
  "else"
  "elsewhere"
  "entirely"
  "especially"
  "etc"
  "even"
  "ever"
  "evermore"
  "exactly"
  "example"
  "except"
  "fairly"
  "far"
  "farther"
  "followed"
  "following"
  "follows"
  "for"
  "former"
  "formerly"
  "from"
  "further"
  "furthermore"
  "get"
  "gets"
  "getting"
  "given"
  "gives"
  "goes"
  "going"
  "gone"
  "got"
  "gotten"
  "had"
  "happens"
  "hardly"
  "has"
  "have"
  "having"
  "hello"
  "hence"
  "her"
  "here"
  "hereafter"
  "hereby"
  "herein"
  "hereupon"
  "hither"
  "hopefully"
  "how"
  "howbeit"
  "however"
  "ignored"
  "immediate"
  "inasmuch"
  "inc"
  "increase"
  "increasingly"
  "indeed"
  "indicate"
  "indicated"
  "indicates"
  "insofar"
  "instead"
  "into"
  "its"
  "itself"
  "just"
  "keeps"
  "kept"
  "know"
  "known"
  "knows"
  "lastly"
  "lately"
  "latter"
  "latterly"
  "lest"
  "let"
  "like"
  "liked"
  "likely"
  "likewise"
  "little"
  "look"
  "looks"
  "ltd"
  "main"
  "mainly"
  "may"
  "maybe"
  "meantime"
  "meanwhile"
  "merely"
  "might"
  "mine"
  "minus"
  "miss"
  "more"
  "moreover"
  "most"
  "mostly"
  "mrs"
  "much"
  "must"
  "myself"
  "name"
  "namely"
  "near"
  "nearly"
  "necessary"
  "need"
  "needs"
  "neither"
  "never"
  "never"
  "neverless"
  "nevertheless"
  "nine"
  "nobody"
  "non"
  "none"
  "nonetheless"
  "noone"
  "no-one"
  "nor"
  "normally"
  "not"
  "nothing"
  "notwithstanding"
  "now"
  "nowhere"
  "obviously"
  "off"
  "often"
  "okay"
  "once"
  "ones"
  "only"
  "onto"
  "opposite"
  "or"
  "otherwise"
  "ought"
  "our"
  "ours"
  "ourselves"
  "out"
  "over"
  "own"
  "particular"
  "particularly"
  "per"
  "perfectly"
  "perhaps"
  "placed"
  "please"
  "plus"
  "possible"
  "presumably"
  "probably"
  "provided"
  "provides"
  "que"
  "quickly"
  "quite"
  "rather"
  "really"
  "reasonably"
  "recently"
  "regarding"
  "regardless"
  "regards"
  "relatively"
  "respectively"
  "right"
  "said"
  "same"
  "say"
  "says"
  "secondly"
  "see"
  "seeing"
  "seem"
  "seemed"
  "seeming"
  "seems"
  "seen"
  "self"
  "selves"
  "sensible"
  "sent"
  "serious"
  "seriously"
  "shall"
  "she"
  "should"
  "since"
  "somebody"
  "somehow"
  "someone"
  "something"
  "sometime"
  "sometimes"
  "somewhat"
  "somewhere"
  "soon"
  "sorry"
  "specified"
  "specify"
  "specifying"
  "such"
  "sup"
  "sure"
  "surely"
  "take"
  "taken"
  "taking"
  "tends"
  "than"
  "thank"
  "thanks"
  "thanx"
  "that"
  "thats"
  "the"
  "their"
  "theirs"
  "them"
  "themselves"
  "then"
  "thence"
  "there"
  "thereafter"
  "thereby"
  "therefore"
  "therein"
  "theres"
  "thereupon"
  "these"
  "they"
  "thing"
  "things"
  "think"
  "this"
  "thorough"
  "thoroughly"
  "those"
  "though"
  "thought"
  "thoughts"
  "thrice"
  "thru"
  "thus"
  "thusly"
  "together"
  "too"
  "took"
  "tried"
  "tries"
  "truly"
  "try"
  "trying"
  "twice"
  "two"
  "undoing"
  "unfortunately"
  "unless"
  "unlike"
  "unlikely"
  "until"
  "unto"
  "upon"
  "upwards"
  "use"
  "useful"
  "uses"
  "using"
  "usually"
  "utterly"
  "value"
  "versus"
  "very"
  "via"
  "viz"
  "vs"
  "want"
  "wants"
  "was"
  "way"
  "we"
  "welcome"
  "went"
  "were"
  "what"
  "whatever"
  "when"
  "whence"
  "whenever"
  "where"
  "whereafter"
  "whereas"
  "whereby"
  "wherein"
  "whereupon"
  "wherever"
  "whether"
  "which"
  "whichever"
  "while"
  "whilst"
  "whither"
  "who"
  "whoever"
  "wholly"
  "whom"
  "whomever"
  "whose"
  "why"
  "wish"
  "with"
  "within"
  "without"
  "wonder"
  "wondered"
  "wondering"
  "would"
  "wouldn't"
  "yes"
  "yet"
  "you"
  "your"
  "yours"
  "yourself"
  "yourselves"
)

(defparameter *tag-suggestions*
  '(("appl" ("fruit" "produce"))
    ("massag" ("health" "service"))
    ("reiki" ("health"))
    ("book" ("book"))
    ("bike" ("transportation" "bicycle"))
    ("bicycl" ("transportation" "bicycle"))
    ("pant" ("clothing"))
    ("programm" ("technology" "service"))
    ("jar" ("food" "supplies"))
    ("heal" ("health"))
    ("pillow" ("supplies"))
    ("medit" ("spirit"))))

(defun get-tag-suggestions (text)
  (remove-duplicates
    (flatten
      (iter (for word in (stem-text text))
            (appending (cdr (assoc word *tag-suggestions* :test #'string=)))))
    :test #'string=))

(defun all-tags-from-string (string)
  (iter (for tag in (split " " (ppcre:regex-replace-all "," (string-downcase string) " ")))
        (when (ppcre:scan *tag-scanner* tag)
          (collect tag))))

(defun remove-forbidden-tags (tags)
  (remove-if #'forbidden-tag-p tags))

(defun tags-from-string (string)
  (remove-forbidden-tags (all-tags-from-string string)))

(defun intersection-string= (list1 list2)
  (intersection list1 list2 :test #'string=))

(defun nearby-tags (&key base (user *user*))
  (let ((nearby (geo-index-query (getf user :lat)
                                 (getf user :long)
                                 (or (getf user :distance) 50)
                                 :index *resource-geo-index*)))
    (let ((tags (make-hash-table :test 'equalp)))
      (dolist (item nearby)
        (dolist (tag (car item))
          (push (fourth item) (gethash tag tags))))

      (when base
        ; get each base tag's list of items
        ; get intersection of those lists
        ; remove base tags from hashtable
        ; set all remaining tags lists to be intersection of tag list and previous intersection
        (let ((base-items (iter (for tag in base)
                                (reducing (gethash tag tags) by #'intersection-string=)
                                (remhash tag tags))))
          (iter (for (tag tag-items) in-hashtable tags)
                (setf (gethash tag tags)
                      (intersection tag-items base-items)))))


      ; for each tag, number of contents + ordered list of subtags (up to 4)
      
      (iter (for (tag tag-items) in-hashtable tags)
            (collect (list tag
                           (length tag-items)
                           (when (cdr tag-items)
                             (let ((subtags (sort
                                              (iter (for (subtag subtag-items) in-hashtable tags)
                                                    (unless (string= tag subtag)
                                                      (awhen (intersection tag-items subtag-items)
                                                        (collect (cons subtag (length it))))))
                                              #'> :key #'cdr)))
                               (subseq subtags 0 (min (length subtags) 4))))))))))

(defun top-tag-p (tag)
  (member tag *top-tags* :test #'string=))

(defun nearby-top-tags (&key (count 11) (more t) base (user *user*))
  (let* ((tags (sort (remove-if-not #'top-tag-p (nearby-tags :base base :user user) :key #'first) #'> :key #'second))
         (top-tags (subseq tags 0 (min count (length tags))))) 
    (cond
      ((and more (> (length tags) (+ count 1)))
       (nconc top-tags
              (list "more"
                    (reduce #'+ (subseq tags count) :key #'second))
                    (subseq tags count (min (+ count 4) (length tags)))))
      ((and more (= (length tags) (+ count 1)))
       (setf top-tags tags)))
    top-tags))


